import { Sparkles, Map } from "lucide-react";

function RouteSummary({ summary, loading }) {
  if (loading) {
    return (
      <div className="card bg-purple-50 border-purple-200 p-4">
        <p className="text-purple-600 animate-pulse">
          🤖 Generating AI route summary...
        </p>
      </div>
    );
  }

  if (!summary) return null;

  return (
    <div className="card bg-gradient-to-br from-purple-50 to-indigo-50 border-purple-200 p-4">
      <div className="flex items-center gap-2 mb-3 text-purple-700">
        <Sparkles className="w-5 h-5" />
        <h3 className="font-semibold text-lg">AI Route Summary</h3>
      </div>

      <p className="text-gray-700 leading-relaxed whitespace-pre-line">
        {summary}
      </p>

      <div className="mt-4 flex items-center gap-2 text-sm text-purple-600">
        <Map className="w-4 h-4" />
        Generated by LogiBOT based on your optimized route
      </div>
    </div>
  );
}

export default RouteSummary;
